spring:
  datasource:
    url: jdbc:mysql://localhost/test_db1?useSSL=false
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
    
security:
  basic:
    enabled: false
    
doma:
  dialect: MYSQL