-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 21:53:25 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biz_cord
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biz_cord
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biz_cord` DEFAULT CHARACTER SET utf8mb4 ;
USE `biz_cord` ;

-- -----------------------------------------------------
-- Table `biz_cord`.`Room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biz_cord`.`Room` ;

CREATE TABLE IF NOT EXISTS `biz_cord`.`Room` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Status` CHAR(2) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biz_cord`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biz_cord`.`User` ;

CREATE TABLE IF NOT EXISTS `biz_cord`.`User` (
  `Key` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Id` VARCHAR(20) NOT NULL,
  `Pw` VARCHAR(40) NOT NULL,
  `Address` VARCHAR(40) NULL,
  `Name` VARCHAR(40) NULL,
  PRIMARY KEY (`Key`),
  UNIQUE INDEX `id_UNIQUE` (`Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biz_cord`.`UserRelRoom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biz_cord`.`UserRelRoom` ;

CREATE TABLE IF NOT EXISTS `biz_cord`.`UserRelRoom` (
  `UserKey` INT UNSIGNED NOT NULL,
  `RoomId` INT UNSIGNED NOT NULL,
  `Type` CHAR(2) NOT NULL,
  PRIMARY KEY (`UserKey`, `RoomId`),
  INDEX `fk_UserRelRoom_Room1_idx` (`RoomId` ASC),
  CONSTRAINT `fk_UserRelRoom_User`
    FOREIGN KEY (`UserKey`)
    REFERENCES `biz_cord`.`User` (`Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserRelRoom_Room1`
    FOREIGN KEY (`RoomId`)
    REFERENCES `biz_cord`.`Room` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biz_cord`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biz_cord`.`Message` ;

CREATE TABLE IF NOT EXISTS `biz_cord`.`Message` (
  `UserKey` INT UNSIGNED NOT NULL,
  `RoomId` INT UNSIGNED NOT NULL,
  `Content` TEXT NOT NULL,
  `Time` DATETIME NOT NULL,
  PRIMARY KEY (`UserKey`, `RoomId`),
  INDEX `fk_Message_Room1_idx` (`RoomId` ASC),
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`UserKey`)
    REFERENCES `biz_cord`.`User` (`Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_Room1`
    FOREIGN KEY (`RoomId`)
    REFERENCES `biz_cord`.`Room` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biz_cord`.`UserRelMessage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biz_cord`.`UserRelMessage` ;

CREATE TABLE IF NOT EXISTS `biz_cord`.`UserRelMessage` (
  `UserKey` INT UNSIGNED NOT NULL,
  `RoomId` INT UNSIGNED NOT NULL,
  `Time` DATETIME NOT NULL,
  PRIMARY KEY (`UserKey`, `RoomId`),
  INDEX `fk_UserRelMessage_Room1_idx` (`RoomId` ASC),
  CONSTRAINT `fk_UserRelMessage_User1`
    FOREIGN KEY (`UserKey`)
    REFERENCES `biz_cord`.`User` (`Key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserRelMessage_Room1`
    FOREIGN KEY (`RoomId`)
    REFERENCES `biz_cord`.`Room` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
